### ISSUE TITLE
No scroll down on the Posts & Comments page and this leads to difficulties to comment and see more posts.

### ISSUE THREAD

**Issue by WenjunYuAnny** [gcivil-nyu-org/Wednesday-Fall2023-Team-2#103]
You website looks great! Just a small thing, there seems no scroll down for the "Post & Comments" page. This makes the user unable to see the third post of a parking spot.

![image](https://github.com/gcivil-nyu-org/Wednesday-Fall2023-Team-2/assets/130470692/8699d87c-12bd-4387-99c7-d65da938a714)

Also this makes the user unable to comment on the second post if the comment form for the first post is open.
![image](https://github.com/gcivil-nyu-org/Wednesday-Fall2023-Team-2/assets/130470692/8714b3f1-b478-4b02-b191-72c1d7445869)

**Comment by NigelLu** [comment]
Thank you so much for your feedbacks. It means a lot to our team. 

This is indeed an issue we need to address. I will add this to our BUG fix TODOs and resolve this in a later release.

Appreciate your effort to make Parkrowd better!
