### ISSUE TITLE
If a not logged in user comments on a post, the page shows "[object object]" on the comment.

### ISSUE THREAD

**Issue by WenjunYuAnny** [gcivil-nyu-org/Wednesday-Fall2023-Team-2#104]
Another small thing: when a not logged in user posts a comment, I see that something like "[object object]" appearing on your page. (Just in case this is not intentional.)
![image](https://github.com/gcivil-nyu-org/Wednesday-Fall2023-Team-2/assets/130470692/774062aa-5d24-49d7-981f-68e50e302a7d)

**Comment by NigelLu** [comment]
Thank you for spotting this issue. 

We will use `LoginRequiredMixin` alongside with cookie to extract which user is submitting POST requests to alleviate this issue (previously, we have partially relied on URL patterns to tell us which user is submitting a POST request, which has caused many vulnerabilities to Parkrowd).

Appreciate your effort to make Parkrowd better and have a lovely weekend!
