### ISSUE TITLE
User Impersonation for make post

### ISSUE THREAD

**Issue by Dhiren-NYU** [gcivil-nyu-org/Wednesday-Fall2023-Team-2#106]
While making a post I clicked on make post button.
I was taken to this page http://parkrowd-prod.us-west-2.elasticbeanstalk.com/map/post/3013688/test1 since i was logged in with test1 id. I changed url and replaced test1 with test3 and created a post.
This post got created as a post from Test3 user for which i didnt even login.
Hence, Without having access to a users account I can still create posts on their behalf

**Comment by NigelLu** [comment]
Thank you for spotting this issue. It means a lot to Parkrowd.
We will update our app to use cookie to extract which user is submitting POST requests to alleviate this issue. Also, we will add `LoginRequiredMixin` to some of the POST views to check for user access privilege.
