### ISSUE TITLE
Large image is not available

### ISSUE THREAD

**Issue by Zhiyuan-Wei** [gcivil-nyu-org/Wednesday-Fall2023-Team-2#110]
When I upload a image, it shows this:

![large_img](https://github.com/gcivil-nyu-org/Wednesday-Fall2023-Team-2/assets/120235952/3e2a7bbd-d4aa-41b3-a393-1b9cb8140eda)

Maybe set a image size limit or a image name limit?

**Comment by NigelLu** [comment]
Thank you for spotting this issue. As of now, AWS EB's nginx enforces this on all request that attach a large file to it. To get around this, we might need to configure other storage methods like S3 Buckets for media files. 

As of now, Parkrowd has decided not to support uploading excessively large image files. But still, your feedback is definitely valid and we shall look into this if we have time~

Below is a screenshot from our testing doc, which we added after realizing excessively large files would cause issues.

<img width="762" alt="Screenshot 2023-11-18 at 18 03 54" src="https://github.com/gcivil-nyu-org/Wednesday-Fall2023-Team-2/assets/52246554/2e890270-72df-46dd-9ed9-857fe96ae1b0">
