### ISSUE TITLE
User login status is not checked, which makes app vulnerable to attack

### ISSUE THREAD

**Issue by khamseaffan** [gcivil-nyu-org/Wednesday-Fall2023-Team-2#111]
I noticed a problem in that the application is vulnerable to DoS attack:

http://parkrowd-prod.us-west-2.elasticbeanstalk.com/map/parking/add-spot/test1/?lat=40.69617299299323&lon=-73.98511352059778

how to generate bug:
1: open the link try changing the lat and log
2: add new spot form will open and then u can add a new spot

point to note is that you are not logged in to the application and are still able to submit the form and it is visible on the map. that way attacker can start a bot and create random spots on the map.

the solution will be whenever you are performing any such operation you can check for user login status.

**Comment by NigelLu** [comment]
Thank you for spotting this issue. It means a lot to Parkrowd.
We will update our app to use cookie to extract which user is submitting POST requests to alleviate this issue (not just for verification, but all other POST). Also, we will add `LoginRequiredMixin` to some of the POST views to check for user access privilege.
