### ISSUE TITLE
Unable to navigate the app on phone

### ISSUE THREAD

**Issue by himanshu1196** [gcivil-nyu-org/Wednesday-Fall2023-Team-2#112]
What I did : visited the home URL on my phone
What went wrong : I could not find a way to move away from the map - all actions like clicking/dragging just change the map and there is no way to navigate the site currently.
Since most of the users would use their phones to browse the app and report/view parking spots, it might be useful to fix the rendering on phones. Focusing on the nav bar when the page loads could be a solution
![WhatsApp Image 2023-11-17 at 8 44 38 PM](https://github.com/gcivil-nyu-org/Wednesday-Fall2023-Team-2/assets/14277620/09c02e89-e44b-49ab-8338-79846462c09b)

**Comment by NigelLu** [comment]
Thank you for dedicating your effort in testing Parkrowd~

Currently, we have not offered support for mobile devices and Parkrowd is best experienced via a 16:9 or 4:3 ratio-ed screen like you would see in most modern day monitors or laptops.

Again, your piece of advice is absolutely relevant and we appreciate your effort.
