### ISSUE TITLE
Users can submit for verification on behalf of other users 

### ISSUE THREAD

**Issue by himanshu1196** [gcivil-nyu-org/Wednesday-Fall2023-Team-2#114]
What I did : Navigated to verification section for my user. Changed the url to that for user2 (http://parkrowd-prod.us-west-2.elasticbeanstalk.com/users/verification/test4 to http://parkrowd-prod.us-west-2.elasticbeanstalk.com/users/verification/test2)

What went wrong : I was able to submit a verification request on behalf of user2.

![Screenshot (108)](https://github.com/gcivil-nyu-org/Wednesday-Fall2023-Team-2/assets/14277620/3868ba78-c5d9-4aea-9272-1a679f8c586d)

**Comment by NigelLu** [comment]
Thank you for spotting this issue. It means a lot to Parkrowd.
We will update our app to use cookie to extract which user is submitting POST requests to alleviate this issue (not just for verification, but all other POST).
